### ISSUE TITLE
Remove level cap for anvil repair penalty, add static repair cost

### ISSUE THREAD

**Issue by orangeandblack5** [exaskye/Fabrication-Features#102]
Currently, it is possible to disable the prior work penalty - but what if, instead, you would prefer to have there be a prior work penalty, but still avoid anvils becoming unusable?

Currently, when you place an item with too high of a prior work penalty into an anvil (such that the enchantment cost would be over 40), it simply tells you that any changes would be "Too expensive!" and doesn't let you do anything. My thought is that ideally Fabrication could allow an unlimited cap on the levels required by an anvil when working on an item, such that you would be able to spend 42 levels, 52 levels, or even 102 levels on an item upgrade if you wanted to and had the experience levels to do so.

Additionally, this would pair very well with a setting similar to balance.anvil_rename_always_costs_one, in which perhaps an item _repair_ always costs 5 levels or some similar number, ignoring the prior work penalty tag entirely. This would allow players to use anvils to repair items without driving up costs for combining enchantments, and prevent the prior work penalty from preventing repairs.

The addition of these two settings would also allow the settings to disable mending to be utilized with much less of an impact on the player's endgame, allowing them to more easily customize and repair endgame equipment in a world devoid of mending, reducing the amount of busywork they need to do and adding more emotional weight behind the arms and armor they've spent so much time and so many levels on.

**Comment by SFort** [comment]
> perhaps an item _repair_ always costs 5 levels or some similar number

should probably open a seperate issue for that, but you'll probably be waiting untill features get configs
