### ISSUE TITLE
Show held items while swimming in boat by knuxify

### ISSUE THREAD

**Issue by SFort** [exaskye/Fabrication-Features#23]
Not sure how hard this would be to implement, but it's something that might be useful:

When you're swimming in a boat (as in pressing W to move forward, just sitting in the boat still shows the items), the items you're holding are hidden from view. This can be quite a pain when making maps for example, since you have to stop all the time to check if you're not going too far off with your map.

Thus, I propose a feature which would show the items, even when swimming.

I suppose this feature could be disabled on simpler profiles by default, for those who like to see the boat animation :p

> https://github.com/unascribed/Fabrication/discussions/171

**Comment by exaskye** [comment]
unascribed/Fabrication#232 merged and released with v1.3.5-pre1.
