### ISSUE TITLE
Villagers Follow Emerald Blocks

### ISSUE THREAD

**Issue by t0mtee** [exaskye/Fabrication-Features#51]

**Comment by t0mtee** [comment]
Can you send me a build please?

**Comment by SFort** [comment]
[fabrication-pre-release.zip](https://github.com/unascribed/Fabrication-Features/files/6495238/fabrication-pre-release.zip)

**Comment by t0mtee** [comment]
thanks!

**Comment by t0mtee** [comment]
@SFort hey sorry for the late response but i'm trying this out client side now (used to use it server side, was fine then) however I get a crash on boot [Link](https://pastebin.com/zmZ3JUMR). I've tried deleting my config however issue still occurs, it doesn't occur after disabling fabrication and it doesn't occur on 1.3.4

**Comment by SFort** [comment]
try setting woina.dirt_screen to false 
i'm farily certain it's unrelated to this feature so maybe open a issue on the [issue tracker](/unascribed/Fabrication/issues/new/choose)
also there is now an [official pre-release](/unascribed/Fabrication/releases)
(althought it won't fix the issue just felt like mentioning it)

**Comment by t0mtee** [comment]
> 
> 
> try setting woina.dirt_screen to false
> i'm farily certain it's unrelated to this feature so maybe open a issue on the [issue tracker](/unascribed/Fabrication/issues/new/choose)
> also there is now an [official pre-release](/unascribed/Fabrication/releases)
> (althought it won't fix the issue just felt like mentioning it)

yeah that didn't work, i'm gonna open an issue
