### ISSUE TITLE
A fix for a really old Minecraft bug?

### ISSUE THREAD

**Issue by The-Gmann** [exaskye/Fabrication-Features#55]
Could there be a fix for https://bugs.mojang.com/browse/MC-610? It bugs me so much (no pun intended), so i really wish it could be fixed here.

**Comment by Jamalam360** [comment]
This was fixed in vanilla

**Comment by The-Gmann** [comment]
> This was fixed in vanilla

Not in 1.16.5, which I'm playing. It was only fixed in 1.17 snapshots.

**Comment by Jamalam360** [comment]
Oh ok

**Comment by exaskye** [comment]
This is a lot of changes to make to a part of the code I'm unfamiliar with and it's already fixed in vanilla, so I don't think this will be getting added.
