### ISSUE TITLE
Old mob strafing

### ISSUE THREAD

**Issue by Sailingway** [exaskye/Fabrication-Features#59]
In older versions creepers/skeletons would strafe sideways and around the player when in exploding/shooting distance. Kind present in skeletons in modern versions, but it'd be nice if they strafed around the player when you got closer.

https://youtu.be/TodDV2q5rZQ?t=223
https://youtu.be/4h-CXaJXclg?t=520

**Comment by exaskye** [comment]
The old AI system and new AI system are fundamentally different and this is not really reasonable to port. Skeleton strafing represents Mojang's current best effort on the current AI system.
