### ISSUE TITLE
Title screen dirt background

### ISSUE THREAD

**Issue by samozoid** [exaskye/Fabrication-Features#62]
I Would like to have an option to make the background for the title screen as the dirt background that is used by the options background because another mod interferes with the block logo and I want to use the block logo with the dirt background without using another mod.

https://www.youtube.com/watch?v=Zjs_0h1ajF0

**Comment by SFort** [comment]
Was added in [pull/255](https://github.com/unascribed/Fabrication/pull/225)
but it's not been officially released yet

**Comment by SFort** [comment]
[never mind it just got released](https://github.com/unascribed/fabrication/releases/tag/v1.3.5-pre1)

**Comment by exaskye** [comment]
Partly because I saw this in my email and went "god damn it i should just release that"
