### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by zzn924418** [exaskye/Fabrication-Features#63]
I hope to add a few features
1. The Enchants of the crossbow and bow is compatible . Like crossbow is compatible with Power and Punch, and the bow is compatible with Quick Charge and Piercing. https://www.curseforge.com/minecraft/mc-mods/sneaky-magic
2. Luck is compatible with Silk Touch. Trigger Silk Touch when Sneaking.
3. You can quickly open Shulker Boxes(and Ender Chests and Crafting Tables)，when Right clicking the item while hovering over in your inventory. https://www.curseforge.com/minecraft/mc-mods/quick-shulker

**Comment by exaskye** [comment]
One feature per issue.
