### ISSUE TITLE
Food Stacking and Beta Hunger

### ISSUE THREAD

**Issue by thomasfoolish** [exaskye/Fabrication-Features#69]
just a small thing but, with the addition of instant eat, instant bow, no sprint, etc... to fully restore beta balance, why not add options to replace hunger with restoring health and to remove stacking food?

**Comment by SFort** [comment]
Beta hunger has been a part of fabrication in taggable_players and will be a standalone feature from 3.0 onwards
as for changing stacksize, doing it server-only makes things super jank
