### ISSUE TITLE
Search [request]

### ISSUE THREAD

**Issue by Anoaxx** [exaskye/Fabrication-Features#71]
Mod has have a billions of billions of options, and sometime if i need to find something i lost something like 10 mins to do what i want to do. 

Simple solution: Search option. searching not only in names of options but also in descriptions. 

PS. i was looking for this request, but can't find it. Search on github is very helpful.

**Comment by SFort** [comment]
fabrication is getting to the point where it would not hurt to have tags
(also the ini is searchable)
but ye searchable all catagories tab would be nice

**Comment by exaskye** [comment]
Added in [`ede6f31`](https://github.com/unascribed/Fabrication/commit/ede6f3133a2e87d9bff7230862c7002832af396a) - will be released in v2.0.0-pre4 and backported to 1.16 Soon™
