### ISSUE TITLE
Creepers are immune to explosion damage

### ISSUE THREAD

**Issue by UwUWallaby290** [exaskye/Fabrication-Features#81]
You know when there are multiple creepers attacking you, or in the same closed area, and it could have potential to be a deadly amount of explosions, but they just end up killing each other instead? **It'd be really cool if they were immune to explosion damage**, a small buff that could make them significantly more interesting in those situations overall, and I'd personally love a feature like that. It is just disappointing when they do that
![ea90552d9a118b107406e3c9fe03863e--creeper-minecraft-creepers](https://user-images.githubusercontent.com/88938006/140304198-7105db9b-4ce2-4f86-b0a5-0de36de14062.jpg)
.
this is a really bad res image that I found on google, btu you can see the multiple creepers. Imagine how cool it would be if they all exploded, but they instead kill each other, and in the end only 2-3 of them end up really causing damage. An even cooler feature would be that they light each other with explosions, like when you use a flint and steel in them, but still, no explosion damage would be really cool

**Comment by exaskye** [comment]
Notes to myself/SFort: `weird_tweaks.chaining_creepers`. Mixin to damage and check for explosion damage, if so call the method responsible for exploding the creeper. (Maybe start a shorter fuse like TNT?)
