### ISSUE TITLE
Bubble Pop

### ISSUE THREAD

**Issue by RyanCR03** [exaskye/Fabrication-Features#82]
in 1.13, the "minecraft:bubble_pop" particle appeared at the top of soul sand jets and played the
"minecraft:block.bubble_column.bubble_pop" sound. but a bug caused the particle and sound not to appear.
it adds to the ambience of the jets. also it could be possible that it makes the pop sound/particle whenever a bubble leaves water

**Comment by exaskye** [comment]
This particle and sound event still appear to exist, so this could be added.
