### ISSUE TITLE
Explosion Smoke

### ISSUE THREAD

**Issue by Simple205** [exaskye/Fabrication-Features#83]
Explosions in 1.15 lost its smoke particles and now only has the explosion particles. I found these images on the Mojang bug report website and I think the explosion without smoke looks way worse. 
![image](https://user-images.githubusercontent.com/73256738/142529358-8661b5fb-fe74-4744-9ceb-f04be703db19.png)

**Comment by Simple205** [comment]
![image](https://user-images.githubusercontent.com/73256738/142535536-b8d1f1ee-a97f-44ef-8f6c-fac179e0a416.png)
After looking at the comments it seems the devs removed it because of lag

**Comment by RyanCR03** [comment]
this could still be an option to turn on even if there is lag. the particles `minecraft:cloud` and `minecraft:smoke` still exist
