### ISSUE TITLE
No Hunger

### ISSUE THREAD

**Issue by Zockerhopper** [exaskye/Fabrication-Features#94]
What I am suggesting here is that you could add an option to remove the hunger bar and let food heal hearts instead. When you copple that with Instant Eat it would recreate the System from Beta 1.7.3 and before. As this was a system that was present a long time ago I will also list what food healed how many hearts at that time:

Cooked Porkchop: 4 Full Hearts (8 Health Points)
Apples: 2 Full Hearts (4 Health Points)
Mushroom Stew: 5 Full Hearts (10 Health Points)
Bread: 2 and 1/2 Hearts (5 Health Points)
Golden Apples: 10 Full Hearts (20 Health Points)
Cake (Fully eaten): 9 Full Hearts (18 Health Points) each Bite 1 and 1/2 Hearts (3 Health Points)
Cookie (all 8 eaten): 4 Full Hearts (8 Health Points) each Bite 1/2 Heart (1 Health Point)

Now the other Foods haven't been added yet so you can decide how much they should heal you.

**Comment by exaskye** [comment]
Already exists under Taggable Players as the no_hunger tag.
